version: '2'

services:

  limesurvey:
    image: acspri/limesurvey:3.4.1
    ports:
      - 8082:80
    environment:
      LIMESURVEY_DB_PASSWORD: example
      LIMESURVEY_ADMIN_USER: admin
      LIMESURVEY_ADMIN_PASSWORD: password
      LIMESURVEY_ADMIN_NAME: Lime Administrator
      LIMESURVEY_ADMIN_EMAIL: lime@lime.lime
  mysql:
    image: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306